version: "3.9"
services:
  dns:
    build: .
    hostname: dns
    volumes:
      - ./conf/:/etc/bind/:ro
      - dns-cache:/var/cache/bind
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "127.0.0.1:953:953/tcp"
    command: sleep infinity
volumes:
  dns-cache:
